# Generated by Django 4.1.6 on 2023-02-14 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_question_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradedassignment",
            name="grade",
            field=models.IntegerField(
                validators=[django.core.validators.MaxLengthValidator(200)]
            ),
        ),
    ]
