# Generated by Django 4.1.6 on 2023-02-21 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0005_material"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradedassignment",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="material",
            field=models.FileField(
                upload_to="material/%Y/%m/%d/a7e1171e-0733-42fc-948b-020a0a9f21b2"
            ),
        ),
    ]
