# Generated by Django 3.2.7 on 2023-02-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230212_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='profile_picture',
            field=models.ImageField(default='C:/Users/lenovo/Downloads/default_image.png', upload_to='edu-pictures/'),
        ),
    ]
