# Generated by Django 3.2.7 on 2023-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='profile_picture',
            field=models.ImageField(default='C:\\Users\\lenovo\\Desktop\\E_Learner\\Backend\\media\\edu-pictures\\default_image.png', upload_to='edu-pictures/'),
        ),
    ]
